version: "3"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - micro
    stdin_open: true
    tty: true

networks:
  micro:
